# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c06f26c8dff23ba12bd3b4de24aa50fb695e12498ca9f79ba41a752a71d6db1f3c0bd4af55f2fe653caeb2b41b65f4624a0f465db3cd871c11a40265417279eb

test:
  secret_key_base: 528da2b4cc2a580c468507f83e7f3c75f9409cf603508ca73ac030da6c3c158156320e527bd87a39131d5404a48eb85bbbf81f61d2c0594c1cc13f2c1b2c235c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
